# Generated by Django 4.1.3 on 2022-11-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
