# Generated by Django 4.1.3 on 2022-11-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
