# Generated by Django 4.1.3 on 2022-11-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_date_auction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watch',
            field=models.BooleanField(default=False),
        ),
    ]
