# Generated by Django 4.1.3 on 2022-11-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
