# Generated by Django 4.1.3 on 2022-11-24 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_auction_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watch_users',
            field=models.ManyToManyField(blank=True, related_name='watchlist_auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
